version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tufin/orca-operator
    docker:
      - image: tufinim/circleci-go:master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Generate code from orca_types.go 
          command: |
            operator-sdk generate k8s
      - run:
          name: Build operator
          command: |
            operator-sdk build tufin/orca-operator --image-build-args "--build-arg version=${CIRCLE_BUILD_NUM} --build-arg release=${OPENSHIFT_RELEASE}"
      - run:
          name: Validate artifacts
          command: |
            # create a dummy container which will hold a volume with config
            docker create -v /artifacts --name configs alpine:3.4 /bin/true
            # copy artifact files into this volume
            docker cp orca-operator.0.1.0.clusterserviceversion.yaml configs:/artifacts
            docker cp orca.package.yaml configs:/artifacts
            docker cp deploy/crds/tufin_v1alpha1_orca_crd.yaml configs:/artifacts
            docker run --volumes-from configs tufin/operator-courier operator-courier --verbose verify /artifacts
      - run:
          name: Push docker image
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
            docker push tufin/orca-operator
            
