version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tufin/orca-operator
    docker:
      - image: tufinim/circleci-go:master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: |
            operator-sdk generate k8s
            operator-sdk build tufin/orca-operator --image-build-args "--build-arg version=${CIRCLE_BUILD_NUM} --build-arg release=${OPENSHIFT_RELEASE}"
      - run:
          name: Push docker image
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
            docker push tufin/orca-operator