apiVersion: tufin.io/v1alpha1
kind: Orca
metadata:
  name: orca
spec:
  domain: my-domain
  project: my-project
  namespace: placeholder
  images:
    kite: "registry.connect.redhat.com/tufin/kite"
    monitor: "registry.connect.redhat.com/tufin/monitor"
  ignored_config_maps:
    - kube-system/ingress-gce-lock
    - istio-system/istio-ingress-controller-leader-istio
  endpoints:
    orca: "https://orca.tufin.io"
    guru: "guru.tufin.io:443"
    registry: "registry.tufin.io"
  components:
    dns: false
    conntrack: true
    istio: false
    pusher: true
    syslog: false
    watcher: true
    kube-network-policy: true
  kube_platform: Openshift
status:
  phase:
