apiVersion: apps/v1
kind: Deployment
metadata:
  name: orca-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orca-operator
  template:
    metadata:
      labels:
        name: orca-operator
    spec:
      serviceAccountName: orca-operator
      containers:
        - name: orca-operator
          # Replace this with the built image name
          image: registry.connect.redhat.com/tufin/orca-operator
          command:
          - orca-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "orca-operator"
status:
  phase: