apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: orca-operator
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - orca-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - tufin.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.tufin.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kite
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - networking.tufin.io
  resources:
  - policies
  verbs:
  - '*'
- apiGroups:
  - config.istio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - istio.io
  resources:
  - istioconfigs
  - istioconfigs.istio.io
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  - thirdpartyresources.extensions
  - ingresses
  - ingresses/status
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  - nodes
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - hostaccess
  - hostnetwork
  - node-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conntrack
rules:
- apiGroups:
    - ''
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
    - delete
- apiGroups:
    - ''
  resources:
    - pods/log
    - services
    - nodes
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - statefulsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - deployments
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
  resources:
    - deployments/scale
  verbs:
    - get
    - update
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
    - watch
- verbs:
  - use
  apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
