apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"tufin.io/v1alpha1","kind":"Orca","metadata":{"name":"orca"},"spec":{"components":{"conntrack":true,"dns":false,"istio":false,"kube-network-policy":true,"pusher":true,"syslog":false,"watcher":true},"domain":"generic-bank","endpoints":{"guru":"guru.tufin.io:443","orca":"https://orca.tufin.io","registry":"registry.tufin.io"},"ignored_config_maps":["kube-system/ingress-gce-lock","istio-system/istio-ingress-controller-leader-istio"],"images":{"kite":"registry.connect.redhat.com/tufin/kite","monitor":"registry.connect.redhat.com/tufin/monitor"},"kube_platform":"Openshift","namespace":"tufin-system","project":"openshift4"},"status":{"phase":null}},{"apiVersion":"networking.tufin.io/v1","kind":"Policy","metadata":{"name":"orca","namespace":"placeholder"},"spec":{"mode":"learning","networkPolicyAllowAll":true,"rules":[]},"status":{"phase":null}}]'
    capabilities: Basic Install
    categories: Security
    certified: "true"
    containerImage: registry.connect.redhat.com/tufin/orca-operator
    createdAt: ""
    description: Installs the Orca Agent on the cluster. Orca is a cloud-based security
      monitoring and enforcement platform for Kubernetes.
    repository: https://github.com/Tufin/orca-operator
    support: Tufin
  name: orca-operator.v0.1.154
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Orca Agent configuration
      displayName: Orca
      kind: Orca
      name: orcas.tufin.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      - kind: ReplicaSet
        name: ""
        version: ""
      specDescriptors:
      - description: Your domain in Orca - usually the name of your organization
        displayName: domain
        path: domain
      - description: Your project in Orca - a friendly name for your Kubernetes cluster
        displayName: project
        path: project
      - description: The Namespace for the Orca Agent
        displayName: Orca Agent Namespace
        path: namespace
      - description: The docker images for the Orca Agent
        displayName: Orca Agent images
        path: images
      - description: List of Config Maps to ignore
        displayName: Ignored Config Maps
        path: ignored_config_maps
      - description: Orca Agent Endpoints
        displayName: Endpoints
        path: endpoints
      - description: Control over the Components of the Orca Agent
        displayName: Orca Agent Components
        path: components
      - description: The platform the Orca Agent is deployed on
        displayName: Kubernetes Platform
        path: kube_platform
      statusDescriptors:
      - description: Orca CRD Status
        displayName: Phase
        path: phase
      version: v1alpha1
    - description: Orca Policy configuration
      displayName: Policy
      kind: Policy
      name: policies.networking.tufin.io
      resources:
      - kind: NetworkPolicy
        name: ""
        version: networking.k8s.io/v1
      specDescriptors:
      - description: Toggle between Enforce Mode and Learn Mode
        displayName: Mode
        path: mode
      - description: Set Kubernetes Network Policy to Allow-All in Learn Mode
        displayName: Kubernetes Network Policy
        path: networkPolicyAllowAll
      - description: Orca Policy allowed connections
        displayName: Rules
        path: rules
      statusDescriptors:
      - description: Orca Policy Status
        displayName: Phase
        path: phase
      version: v1
  description: |-
    Tufin Orca is a cloud-based security monitoring and enforcement platform for Kubernetes clusters, containers and microservices.
    The Orca Operator installs Orca resources into your cluster. These work with the Orca cloud application to give the following functionality:
    * Monitor the cluster configuration: namespaces, containers, pods, services, network policies etc.
    * Learn and visualize the cluster connectivity
    * Build a connectivity policy (whitelist)
    * Generate audit reports
    * Alert on unauthorized connections
    * Enforce the connectivity policy in the cluster and on enterpise firewalls surrounding the cluster
    * Integrate into the CI/CD pipeline to learn and update the policy continuously
    * Scan images for vulnerabilities
    ## Deploying the agent
    * Sign up to Orca [here] (https://www.tufin.com/products/tufin-orca#s6)
    * You will be sent an email containing your deployment parameters
    * Complete the deployment following the instructions for generating the agent's secret [here] (https://github.com/Tufin/orca-operator/blob/master/README.md)
  displayName: Tufin Orca Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAIAAADmAupWAAAKDWlDQ1BpY2MAAEiJlZYHVFTXFobPvdMbbYbeht57G3rvIL2KyjBDhxGGjqiIBCMQUUREQJESqoLRUCQWxIKFIKAUa0CCgBKDBVBByUVSV9Z7671/rTP7u3vu3WfPPnet+QEgsZkJCXEwHwDxnGSut6MNPTAomI57BmBABQQgBdSYrKQEa09PN4Doj/hPLY0CaD3e01iv9e/v/6v42eFJLAAgT4Tj2UmseIR7ELZiJXCTAdIGIrm05IR1lkeYxkUaRJixzpEbvN4TLWyDQ7/c4+ttizDyDJ7MZHIjASBmI3l6KisSyRFPIqzNYUdzEB5E2IIVxWQDQEKmANTj47evsxnCymF/qxP5j5phf9ZkMiP/5I3f8kVUJ0+6rlF6NN2WGRcdxmUmh7P/z8n8D4qPS/ljv/UTIIdz/HyQuD4nCeAEPAEd6AIjkA6iEbIFTBCHUBjgIpQMwgE7OTw9ef1h2+0JGdzoyKhkujVyguF0Zw5LU52uq62DTHn9fdjY4u34l10gIfxfubgMABh1yFyO/pULmwSgvQMA3uC/ckpZyFHXA3DFjJXCTd3Iodc/MIAIeAENiCLvmhxQBhpIx4bAFFgBe+ACPIAvCAJbAQtEgXik7zSQBfaAPFAADoIjoBxUgVrQCE6Ds6ATXABXwA1wBwyCEfAITIBp8BIsgCWwAkEQDqJAVEgUkoYUIDVIF2JAFpA95AZ5Q0FQKBQJcaAUKAvaCxVAxVA5VA01Qd9B56Er0C1oCHoATUJz0BvoI4yCyTANloQVYS2YAVvDrrAvvAWOhBPhTDgXPgCXwTXwKbgDvgLfgUfgCfglvIgCKBJKCCWD0kAxULYoD1QwKgLFRe1C5aNKUTWoVlQ3qg91DzWBmkd9QGPRVDQdrYE2RTuh/dAsdCJ6F7oQXY5uRHegr6HvoSfRC+jPGApGAqOGMcE4YwIxkZg0TB6mFFOPacdcx4xgpjFLWCxWCKuENcI6YYOwMdgd2ELscWwbtgc7hJ3CLuJwOFGcGs4c54Fj4pJxebhjuFO4y7hh3DTuPZ6El8br4h3wwXgOPgdfim/GX8IP42fwKwQ+ggLBhOBBYBMyCEWEOkI34S5hmrBC5CcqEc2JvsQY4h5iGbGVeJ34mPiWRCLJkoxJXqRoUjapjHSGdJM0SfpAFiCrkm3JIeQU8gFyA7mH/ID8lkKhKFKsKMGUZMoBShPlKuUp5T0PlUeTx5mHzbObp4Kng2eY5xUvgVeB15p3K28mbynvOd67vPN8BD5FPls+Jt8uvgq+83xjfIv8VH4dfg/+eP5C/mb+W/yzAjgBRQF7AbZArkCtwFWBKSqKKke1pbKoe6l11OvUaRqWpkRzpsXQCminaQO0BUEBQX1Bf8F0wQrBi4ITQighRSFnoTihIqGzQqNCH4Ulha2Fw4X3C7cKDwsvi4iLWImEi+SLtImMiHwUpYvai8aKHhLtFH0ihhZTFfMSSxM7IXZdbF6cJm4qzhLPFz8r/lACllCV8JbYIVEr0S+xKCkl6SiZIHlM8qrkvJSQlJVUjFSJ1CWpOWmqtIV0tHSJ9GXpF3RBujU9jl5Gv0ZfkJGQcZJJkamWGZBZkVWS9ZPNkW2TfSJHlGPIRciVyPXKLchLy7vLZ8m3yD9UICgwFKIUjir0KSwrKikGKO5T7FScVRJRclbKVGpReqxMUbZUTlSuUb6vglVhqMSqHFcZVIVVDVSjVCtU76rBaoZq0WrH1YbUMerG6hz1GvUxDbKGtUaqRovGpKaQpptmjman5istea1grUNafVqftQ2047TrtB/pCOi46OTodOu80VXVZelW6N7Xo+g56O3W69J7ra+mH65/Qn/cgGrgbrDPoNfgk6GRIdew1XDOSN4o1KjSaIxBY3gyChk3jTHGNsa7jS8YfzAxNEk2OWvyq6mGaaxps+msmZJZuFmd2ZS5rDnTvNp8woJuEWpx0mLCUsaSaVlj+cxKzoptVW81Y61iHWN9yvqVjbYN16bdZtnWxHanbY8dys7RLt9uwF7A3s++3P6pg6xDpEOLw4KjgeMOxx4njJOr0yGnMWdJZ5Zzk/OCi5HLTpdrrmRXH9dy12duqm5ct2532N3F/bD7400KmzibOj2Ah7PHYY8nnkqeiZ4/eGG9PL0qvJ5763hneff5UH22+TT7LPna+Bb5PvJT9kvx6/Xn9Q/xb/JfDrALKA6YCNQK3Bl4J0gsKDqoKxgX7B9cH7y42X7zkc3TIQYheSGjW5S2pG+5tVVsa9zWi9t4tzG3nQvFhAaENoeuMj2YNczFMOewyrAFli3rKOsl24pdwp4LNw8vDp+JMI8ojpiNNI88HDkXZRlVGjUfbRtdHv06ximmKmY51iO2IXYtLiCuLR4fHxp/niPAieVc2y61PX37UIJaQl7CRKJJ4pHEBa4rtz4JStqS1JVMQ/54+1OUU75KmUy1SK1IfZ/mn3YunT+dk96foZqxP2Mm0yHz2x3oHawdvVkyWXuyJnda76zeBe0K29W7W2537u7pbMfsxj3EPbF7fszRzinOebc3YG93rmRudu7UV45fteTx5HHzxvaZ7qv6Gv119NcD+/X2H9v/OZ+df7tAu6C0YLWQVXj7G51vyr5ZOxBxYKDIsOjEQexBzsHRQ5aHGov5izOLpw67H+4ooZfkl7w7su3IrVL90qqjxKMpRyfK3Mq6jskfO3hstTyqfKTCpqKtUqJyf+Xycfbx4RNWJ1qrJKsKqj6ejD45Xu1Y3VGjWFNai61NrX1e51/X9y3j26Z6sfqC+k8NnIaJRu/Ga01GTU3NEs1FLXBLSsvcqZBTg6ftTne1arRWtwm1FZwBZ1LOvPgu9LvRs65ne88xzrV+r/B9ZTu1Pb8D6sjoWOiM6pzoCuoaOu9yvrfbtLv9B80fGi7IXKi4KHix6BLxUu6ltcuZlxd7Enrmr0Remerd1vvoauDV+9e8rg1cd71+84bDjat91n2Xb5rfvHDL5Nb524zbnXcM73T0G/S3/2jwY/uA4UDHXaO7XYPGg91DZkOXhi2Hr9yzu3fjvvP9OyObRoZG/UbHx0LGJsbZ47MP4h68fpj6cOVR9mPM4/wnfE9Kn0o8rflJ5ae2CcOJi5N2k/3PfJ49mmJNvfw56efV6dznlOelM9IzTbO6sxfmHOYGX2x+Mf0y4eXKfN4v/L9UvlJ+9f2vVr/2LwQuTL/mvl57U/hW9G3DO/13vYuei0+X4pdWlvPfi75v/MD40Pcx4OPMStoqbrXsk8qn7s+unx+vxa+tJTC5zC9WAIUsOCICgDcNAFCCEPuE+DLi5g2/9ru/gf7mdP4Db3i6LzIEoLYHAP9sADyRWIVERSTyWSHXyPK1ArCe3p/rdyVF6Olu1CJ1ItakdG3tbQAAOBUAPo2tra10rq19QjwM6iEAPUsbPnFdsguInVz3o+Du+Oq/PNpvY87BDKVlW9UAAAADc0JJVAgICNvhT+AAAA5qSURBVGiB1Zh5cBzVmcC/97p7puc+JM2MNLpG0kiWbSyDbMkHdgwIYwhXEGAbCnshJFyBBJYibCActQE2BeFIliwspAJkC8ISDhsHY7DlmMu2LMmHhGzd90ijuY+enr7e2z9EHAd8H3Ltr6bmjzf9vu/7VX/19ZsGerq5YeWqjvaO0x72dIEH+vu7e7rhdJBMp9devQq/HdMwOS0BzwSsJEvV1TN/fs8DP/7Zj32+cnQim4VMJhQOjY4Mf755274NX8RbhkqqFqkgIXRCYaYVRCm9deUtnv0lTe0fVdW5bH6vf/E5vhKf2+NxOhzufA+v14dCod6+3rp5dRzHAUAynX7i0ccHth/gBc2U0sWT8fqiKt7Ij0iC3lD5/hdvvT/4XmmJ72yrHR5EKd1/oPO26ruWNDSkkkMVRsN4NMQQZmgyIFt1OsztDrXXldfbDOYAG37w2ccG+gc3Pfli4/wlXcGgHNNnQbLx5snoRBHv6EhAz96+R3c+VF+34Gx7HRFEKQWAO2+9I7ZBLJvhH5MG83I9QmxkVn4ZAhTNRiwmI2e0cwynKOqX7Z9VGBh/iS9LNJ7j9o2MZNOsx+wAhCIjgV4z/G7dc8XFJWdb6mh8IwwAu3Y1/+GZP46/Gylb5ud5UmwwhMSwz1NACRlLZ3QcuExQkOMI9w06jCYAUIjWPTqhqVjj7IM9A8ICy4t/+C+LxXpWdY7NP4SnaG/f95//8WLru60X1c8pzC9IZ0VJVmPp4bn+iqJcN8uww4MD+TqjoMm9w8EKi1vQpKbOAw1P/XD1DavPlsMJ8W3hKVpbWv7y9jvdb+8+p9BvdjpmeSkGPBCPmuw2E2b16czegVGbzhQQEzoGG5Ah/+YLbrrlX6a9+JPh8MJTiFnxb1v/tuX9jW6JaKqiR0hKpFsHB+zIOK+oysQbFSHuMpqzqrqu+au1f376omUXTGfpJ8fRhKegALKiEEI0TVMkORqPPXPDPbWlVWOjI/PyvBqlCFBISod5zdN44Zobb5yeuqeIJxKfbtq0d3urxWwmhAAFiujfpaimkbyi/Dt+cuehW44t/F3e/PNbwvvNVNQUVdUR1cpygiz562va9u0V5pfddc9PbNYzO7pUTd29e8/W9R9nugK1/llJUfT6igEQAAX45gsAGIx39vWCi73/wfsP7j0ZYQBYveyypfoSymINUUlThkJjc86by+tNRCV7JwdmrFi4ctVK2xmY2OPBic+3fda9pbmQd+Q7XUajUSWapmlhWShw5xPyT0dajmVHM4LBaO0Itv/ikYemFk9SeGB46Kkb7rp87mJJUzSNxKnm8xanMkIynUSylJDTYU0sXTLv6uuvzXU6T91TEDM7d+zc9sHHgY/2IIv9vPmzi70um8kiKwoFYDAzGBwr8/s1TQMAhBBCiEGIENI5EZi/YMl4IPBV15dPPP3kyQsDwO59e9+++dHvLVl8IBL0uguiibCFZXJMplRW9JSWsBhHItGWoZ6SpbVXXXuN82S1e/p6P9mwcc87Ta6gLsdsQxyGKq+O0aXEpNGKK0uKTbxR1TRNVVNYc1rtsiJnZVlUFEklrN4UjI5azDaffwYl8GXHZw8/8cjJCwPAxo82/umuX523sNam11l5AyCMgPbEw77CQqCAGcak17e1t48TuWZp3Xnn18+fPw8jfDyRJ8Ohz5q27diwWdw24jXm2p12iigFSGqibVYlJhQjLKtqPBN1OAzlnnyJam39XTVz61VAZrON5w1GvaF/uLuirLiv64CJ00U1ZWR04vq7V56SMACsX7d+/8vv1Z1zjkQ0FuOe8TF/9QwGIQBgGWYsNDkSCM1bsFBV5MBksD8WOGdZ/eJlS/I9noMRCCVCRpRlKRaNZTOZ8WCwaeOnoY87SmSH3W5jeU4DMlUkphDWq/kVfk1TEUVyRlI0FeXpCupLxnb08XZnbc08VVEIJQihaCyqNxCLyZrJiMPd+2f45+zo6lixdgV7KrYAcOVVV+a6XB8+/vwlNXXhVJzyOp7TaURDCHWPjNj0NoPVotfrMEblpb5KX3l4IPJO8yspG6qq9EdCoWQkrsbTWiQtZyUxmtBjTEETIomqMp8OcelolopZHun0Oo4CxYBYqxlUGp+IcXn6iktmz1owp8Tv07Fc57ntn//+g+GRAa+3GGmUECqIUavJHUlE3JWFy5evFrqiTNtuQsmp3uEpBoYGH7n57msuuCIem6zyetNZsW8k4HV4slIW59psZouiyLIkaYqcyQjJRCw+EohMJhbV1MiqRhBRqWY0cg6z2czzPeMT2aRQqOcnQM3NyyMaicaTsUgKZ2gqJGiV+a4ZnkVXLiv0FVntNqBACGE57i/PvcKMJrOqHKck31eVSMaL/J6CmaXl1X6j0QgAFOjmDzZZPLbTIwwA8UT8uYefypXZcq9nYDToNNtUVRkJjfvLy1igeszoOC6ZTqWiMSejz6jy+GBEtuNyj5vXcya9HiNMCEEIdY0GWczkKLKeYSeljM7pcNkdSTETp9pYKlmqMbZCF2hUVVUAAIQRQlmihBKSxWhEAFRUxiF1/QO3F/uKWeaf+vfVl19pvK7xtAkDgEa0xx5+NNm0b1l9PSGqkdPFqeor8FKAWDo5OR7ksqpBr5OBdE2M2SbNKRCXXDwT/t5lCCCjyMFw2moyxwIjRTY7i/FYPNadkRdesizPntPSvL0cdArR4JCSWYy7IpNz5tapiiKmhNzFVfVXNTAM863a2lrboqFww4rlxzUzjxMGM//+5K9q1l4+PhHINVtTWdHr9qREcd+B/WO9AzQr8VYDbzUUFbjN2MCxnB2b2zr62L8XhxCKJlNWg4nDOAWgZ9hAKjExrrrjhgOf7grHoigtAEYIIcD/+EiaYnZ7ZDGbzoqVN16w6JpLvmuryMrmTZ80rFgOp/IcPgqbNm9ue+5PrgKPTEkyGi1ze0wmo4U3EEIopSzHfrp1dx61U6CZjFRan5fvdGqEcCzbPjBcYHcRSsJCKjsezMR0Jp2eAsUETWRiXC4uysuxmoxGnR4ACCEY44HIZFFxla7UufCmy61HONI+/5tnb7vzdoPBCACnOqUPyyUNDfl5rnvX3Hb7DxrL7A6WAAZENEKAAoCkyoyEQQcAYDbyB9oC7gY7AGiaBhQDUEJpOpGMhVWP0apRAgDAIAUpHtEd7s9MMEkwkJxcS47FoicopdKiS2trLlx4pPeGX335Vd2CBVO2AHA6W/pQ5tTMeX3D/4YLrLN/ttZ+xVLV54mKgpgSkKwKYpYI3xx6CVAnNu/p7NdzXDARd1ntoiL3Dw4VMlabndcIBQAG4fFMJN+YQxDhOc6CjbasOdqaaNmyv89Cr/31vXOPbBsOhVuady1avOjgyhlp6UPzvfryf9/7wL/qdfpUOh0cHBluax9q2TexPchlKWgUM5jVc1lNqVzqTWWylLDR8ZDX5CAAKTkTC0oGVi8RJS1ncg02QimmSIwKOIcvuqLm/NWX5RcXHiX71i1bW1tafnrvTzmdbpqEASCbzT7z66dX3bCqwu+fWpFUJRmNxSYigd7B2OBEqD8Qae+XJQVcOF8z5xitKtUoAMcw7QOjHt7Zn5ooM3sUSZZVNaIkLvq3G2u/v9Rusx8laV9P7/p16xYsXLjwkHs7xRkXnuKNP75uMpuuubbxsO/oKUDTpqb3HnveV1Bo43hWBoaADjND8YgU1XiGo2ZOX57rKC6YuaJ2/oK6oyTKZDLvv/sex3KN113LsN8e1zBtwgDQ+fXXH65bf9PaNQVe77d+2t/eObp3fGTHF46sEkaqp8CDNJqOJzu6u1WT9dy6eTlet5EzZHRyQ+OlR0nR2tr6edO2xpXXFRUXHema6RMGAKDw8ksvFXoLv3/l5QfX9rd39m3vz/O42nd86Q0nMMuOxSLEYWDNloLC0rCYLvNVqLISkRJX/LARH2HKRqOxrb9/Y4iK9/3ywaOXcKam9OFBcNsdtxeXljz+y0eFtAAA/T19fdv7HDkOVVF4pxMIiWfSMseYsclIOCUrsYomy0owEmpYfdlhbQnAlnc//Piep0Jbdl/ceOUxSzgjz+GjM2Nm9VWNP5hTPPO1/3m9d3dv9azZqqoyLMvw/P5o0FNY4jPbVE1FANmxIDboWluaVz94q8loOhhBIyQejQaGJrq6OuMfN7sJ57RYug1jM6urj5l9Wlu6p6dnw4cbAl8P+Vwls6tnY4QlRYqkky53fv+eVoeQjkvE7XAefDXFIiaWSc6/+/qKSr8gCMODQ+0d7emO0Y7Wjol2CWeUFRd58/JyNUr0iNmpF37x7JPHrGGahH/32982ffCJy5C7dNESs8WSFpKqrFnMZpvFtrNtp03JznF5gWU6x8aK8gqm/sFjAls6mgsunpebk6PKitFkLC3zvfnaGzN2IGKAEKRNRpusyRSrVrNeScRnPbT20uXLj1nJNLV0be28WP/kspnnlxaVsixDgSKEWYbt7O2cW1ZuNJr6DnSU2ZwMQhhjTFEqldoy0fnIa78pcHsOjfPCmod8jso4Uu18jqwpBCFrfl48K4yU8fc1XHw8lUxrS3+1c/vupuZ8yKk/rx6zuKu/Kzk5ZrPZKSEU46H9HTpN8+QVNe9pw4vLHnjw59/aHo1FL3T6Lr94pSPP6fTk2HJs+bmu7buac8+fsWbtmuOsYXofSwAA0NPXu+7N98wpLhOddLvcGDCDMcswLKf7um1XV//Aj156bPGChd/deP899xVEYWbtuVaDWSNEkeS3Nq2774XHqqtmHH/2syA8RTgSTguCoqqqooiCKGezRCOiKNbUzs3Nyf3u9ev/+te+VzfOnT27e2zIU1EhCpnPAh3PvvQCr+dPKO9ZEz4hRkZHf1T0vVVrVkWEZEaTDiQnLrrx6ltuueUkQv3/EO7r69u/72tvRanb5bLb7Eb+xO7qofwfuoM2VtuVumYAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - orca-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - tufin.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - networking.tufin.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: orca-operator
      - rules:
        - apiGroups:
          - networking.k8s.io
          resources:
          - networkpolicies
          verbs:
          - '*'
        - apiGroups:
          - networking.tufin.io
          resources:
          - policies
          verbs:
          - '*'
        - apiGroups:
          - config.istio.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - istio.io
          resources:
          - istioconfigs
          - istioconfigs.istio.io
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - thirdpartyresources
          - thirdpartyresources.extensions
          - ingresses
          - ingresses/status
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - endpoints
          - pods
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - namespaces
          - nodes
          - secrets
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - hostaccess
          - hostnetwork
          - node-exporter
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: kite
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
          - delete
        - apiGroups:
          - ""
          resources:
          - pods/log
          - services
          - nodes
          - namespaces
          - persistentvolumes
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - cronjobs
          - jobs
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          - daemonsets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments/scale
          verbs:
          - get
          - update
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: monitor
      deployments:
      - name: orca-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: orca-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: orca-operator
            spec:
              containers:
              - command:
                - orca-operator
                env:
                - name: WATCH_NAMESPACE
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: orca-operator
                - name: RELATED_IMAGE_TUFIN_ORCA_OPERATOR
                  value: registry.connect.redhat.com/tufin/orca-operator:production
                - name: RELATED_IMAGE_TUFIN_MONITOR
                  value: registry.connect.redhat.com/tufin/monitor:production
                - name: RELATED_IMAGE_TUFIN_KITE
                  value: registry.connect.redhat.com/tufin/kite:production
                image: registry.connect.redhat.com/tufin/orca-operator:production
                imagePullPolicy: Always
                name: orca-operator
                resources: {}
              serviceAccountName: orca-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - tufin
  - orca
  - security
  labels:
    operated-by: orca-operator
  links:
  - name: Tufin
    url: https://www.tufin.io
  maintainers:
  - email: support@tufin.com
    name: Tufin
  maturity: beta
  minKubeVersion: 1.11.0
  provider:
    name: Tufin
  replaces: orca-operator.v0.1.140
  selector:
    matchLabels:
      operated-by: orca-operator
  version: 0.1.154
